### ISSUE TITLE
Deploy da aplicação

### ISSUE THREAD

**Issue by matheralvs** [netosouza22/pomodoro#1]
Seria muito interessante ver essa aplicação no ar, @netosouza22 🚀.

**Comment by netosouza22** [comment]
Opa @matheralvs, já está no github pages, você não está conseguindo acessar?

**Comment by matheralvs** [comment]
> Opa @matheralvs, já está no github pages, você não está conseguindo acessar?

acabei de visualizar, boaaaa 🚀
